### ISSUE TITLE
Termux ile İP-Tracer kurma

### ISSUE THREAD

**Issue by Redsparta** [Redsparta/siber-g-venlik#1]
İlk önce termux'a Python kurulmalı. Kurulumdan sonra aşağıdakiler yazılmalı.
$ git clone https://github.com/Rajkumrdusad/IP-Tracer.git
$ ls
$ cd IP-Tracer/
$ ls 
$ chmod 777 install
$ sh install
Bütün işlemlerden sonra 
$ IP-TRACER 
Yazılırsa takip kodları çalışacaktır.

___İYİ DERSLER___

**Comment by Enes4xd** [comment]
Termux kurulum kodları
